import type { Meta, StoryObj } from "@storybook/react-vite";
import * as chrome from "../chrome";

/* Generated by tools/gen-component-stories.mjs from chrome.tsx's own prop types,
   default values and JSDoc. Do not hand-edit: `npm run gen:stories -- --check`
   will fail and the next run will overwrite it. To change the text on the docs
   page, edit the comment above `Masthead` in chrome.tsx. */
const meta = {
  title: "05 Patterns/01 Masthead",
  component: chrome.Masthead,
  parameters: {
    layout: "fullscreen",
    docs: {
      description: {
        component:
          "wordmark, nav, CTA, search. Wide: inline nav (optional mega). Narrow: same facts in a sheet behind Menu. Graceful degradation, not a restructured mobile chrome.",
      },
    },
  },
  argTypes: {
    brand: {
      control: "text",
      description: "Wordmark text.",
      table: {
        defaultValue: {
          summary: "BRAND",
        },
      },
    },
    navItems: {
      control: "object",
      table: {
        defaultValue: {
          summary: "NAV",
        },
      },
    },
    navLabel: {
      control: "text",
      description: "Aria label for the primary nav.",
    },
    withMegaMenu: {
      control: "boolean",
      description: "Swaps the inline nav for the mega menu, wide and compact alike.",
    },
    megaMenu: {
      control: "object",
      table: {
        defaultValue: {
          summary: "MEGA",
        },
      },
    },
    megaTrigger: {
      control: "text",
      description: "The nav item that owns the panel; every other item is a plain link.",
      table: {
        defaultValue: {
          summary: "MEGA_TRIGGER",
        },
      },
    },
    megaActions: {
      control: "object",
      table: {
        defaultValue: {
          summary: "MEGA_ACTIONS",
        },
      },
    },
    megaColumns: {
      control: "inline-radio",
      options: [1, 2, 3, 4],
    },
    showSearch: {
      control: "boolean",
    },
    showContactCta: {
      control: "boolean",
    },
  },
  args: {
    brand: chrome.BRAND,
    navItems: chrome.NAV,
    navLabel: "Primary",
    withMegaMenu: false,
    megaMenu: chrome.MEGA,
    megaTrigger: chrome.MEGA_TRIGGER,
    megaActions: chrome.MEGA_ACTIONS,
    megaColumns: 3,
    showSearch: true,
    showContactCta: true,
  },
} satisfies Meta<typeof chrome.Masthead>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  name: "Masthead",
};
