import type { Meta, StoryObj } from "@storybook/react-vite";
import * as Masthead from "../Masthead";

/* Generated by tools/gen-component-stories.mjs from Masthead.tsx's own prop types,
   default values and JSDoc. Do not hand-edit: `npm run gen:stories -- --check`
   will fail and the next run will overwrite it. To change the text on the docs
   page, edit the comment above `Masthead` in Masthead.tsx. */
const meta = {
  title: "05 Patterns/01 Masthead",
  component: Masthead.Masthead,
  parameters: {
    layout: "fullscreen",
    docs: {
      description: {
        component:
          "wordmark, nav, CTA, search. Wide: inline nav (optional mega). Narrow: same facts in a sheet behind Menu. Graceful degradation, not a restructured mobile chrome.",
      },
    },
  },
  argTypes: {
    brand: {
      control: "text",
      description: "Wordmark text.",
      table: {
        defaultValue: {
          summary: "BRAND",
        },
      },
    },
    navItems: {
      control: "object",
      table: {
        defaultValue: {
          summary: "NAV",
        },
      },
    },
    navLabel: {
      control: "text",
      description: "Aria label for the primary nav.",
    },
    withMegaMenu: {
      control: "boolean",
      description: "Swaps the inline nav for the mega menu, wide and compact alike.",
    },
    megaMenu: {
      control: "object",
      table: {
        defaultValue: {
          summary: "MEGA",
        },
      },
    },
    megaTrigger: {
      control: "text",
      description: "The nav item that owns the panel; every other item is a plain link.",
      table: {
        defaultValue: {
          summary: "MEGA_TRIGGER",
        },
      },
    },
    megaActions: {
      control: "object",
      table: {
        defaultValue: {
          summary: "MEGA_ACTIONS",
        },
      },
    },
    megaColumns: {
      control: "inline-radio",
      options: [1, 2, 3, 4],
    },
    megaInitialOpen: {
      control: "boolean",
      description: "The mega panel open on first render (wide header only).",
    },
    showSearch: {
      control: "boolean",
    },
    searchLabel: {
      control: "text",
      description: "The search field's accessible name. Left out, it is “Search” and the brand, so a site named in `brand` is the site searched.",
    },
    showContactCta: {
      control: "boolean",
    },
    contactLabel: {
      control: "text",
      description: "The contact button's label (“Contact us”, “Book a call”).",
      table: {
        defaultValue: {
          summary: "CONTACT_CTA_LABEL",
        },
      },
    },
  },
  args: {
    brand: Masthead.BRAND,
    navItems: Masthead.NAV,
    navLabel: "Primary",
    withMegaMenu: false,
    megaMenu: Masthead.MEGA,
    megaTrigger: Masthead.MEGA_TRIGGER,
    megaActions: Masthead.MEGA_ACTIONS,
    megaColumns: 3,
    megaInitialOpen: false,
    showSearch: true,
    showContactCta: true,
    contactLabel: Masthead.CONTACT_CTA_LABEL,
  },
} satisfies Meta<typeof Masthead.Masthead>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  name: "Masthead",
};

export const OnionSkin: Story = {
  name: "Onion skin (Figma)",
  parameters: {
    docs: { description: { story: "The Figma component laid over this one, at the 1024px section width it was drawn at. Switch Onion in the toolbar. The arguments that pick the skin are container, withMegaMenu, showSearch, showContactCta." } },
    onion: {
      component: "Masthead",
      skin: (a: Record<string, unknown>, ctx: { width: number }) => `${ctx.width < 896 ? "narrow" : "wide"}-${a.withMegaMenu}-${a.showSearch}-${a.showContactCta}.png`,
    },
  },
};
