import type { Meta, StoryObj } from "@storybook/react-vite";
import * as Masthead from "../Masthead";

/* Generated by tools/gen-component-stories.mjs from Masthead.tsx's own prop types,
   default values and JSDoc. Do not hand-edit: `npm run gen:stories -- --check`
   will fail and the next run will overwrite it. To change the text on the docs
   page, edit the comment above `ContactCta` in Masthead.tsx. */
const meta = {
  title: "05 Patterns/03 Contact CTA",
  component: Masthead.ContactCta,
  parameters: {
    layout: "fullscreen",
    docs: {
      description: {
        component:
          "the persistent conversion affordance in the header's trailing edge.",
      },
    },
  },
  argTypes: {
    children: {
      control: false,
      description: "Slot — composed elements, not text.",
      table: {
        defaultValue: {
          summary: "CONTACT_CTA_LABEL",
        },
      },
    },
    variant: {
      control: "inline-radio",
      options: ["solid", "outline", "quiet"],
    },
    size: {
      control: "inline-radio",
      options: ["sm", "md", "lg"],
    },
  },
  args: {
    children: Masthead.CONTACT_CTA_LABEL,
    size: "sm",
  },
} satisfies Meta<typeof Masthead.ContactCta>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  name: "Contact CTA",
};

export const OnionSkin: Story = {
  name: "Onion skin (Figma)",
  args: {"children":"Button"},
  parameters: {
    docs: { description: { story: "ContactCta is a Button with a default label and size sm, so its skins are the Figma Button's, laid over this one. Switch Onion in the toolbar; variant and size in Controls pick the skin." } },
    onion: {
      component: "Button",
      skin: (a: Record<string, unknown>) => `${a.variant ?? "solid"}-${a.size ?? "sm"}-default.png`,
    },
  },
};
