import type { Meta, StoryObj } from "@storybook/react-vite";
import * as chrome from "../chrome";

/* Generated by tools/gen-component-stories.mjs from chrome.tsx's own prop types,
   default values and JSDoc. Do not hand-edit: `npm run gen:stories -- --check`
   will fail and the next run will overwrite it. To change the text on the docs
   page, edit the comment above `HeaderSearch` in chrome.tsx. */
const meta = {
  title: "05 Patterns/04 Header search",
  component: chrome.HeaderSearch,
  parameters: {
    layout: "fullscreen",
    docs: {
      description: {
        component:
          "a disclosure that eases open instead of swapping the DOM.",
      },
    },
  },
  argTypes: {
    label: {
      control: "text",
      description: "Accessible name for the field.",
      table: {
        defaultValue: {
          summary: "HEADER_SEARCH_LABEL",
        },
      },
    },
    placeholder: {
      control: "text",
      description: "The one placeholder the kit keeps. The label is hidden here, so once the field opens this is its only visible cue; it echoes the label and never replaces it. Text tertiary on the input's surface is in the contrast gate (input/placeholder). Every other field has a visible label and none.",
    },
    openLabel: {
      control: "text",
      description: "Name of the submit button while collapsed, and once open.",
    },
    submitLabel: {
      control: "text",
    },
    initialOpen: {
      control: "boolean",
      description: "Whether the field starts expanded.",
    },
  },
  args: {
    label: chrome.HEADER_SEARCH_LABEL,
    placeholder: "Search",
    openLabel: "Open search",
    submitLabel: "Search",
    initialOpen: false,
  },
} satisfies Meta<typeof chrome.HeaderSearch>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  name: "Header search",
};

export const OnionSkin: Story = {
  name: "Onion skin (Figma)",
  parameters: {
    docs: { description: { story: "The Figma component laid over this one, closed and open, in the 1024px form the story gives it: the control sits at the left, one quiet icon button closed, a 224px input and the button open. Switch Onion in the toolbar." } },
    onion: {
      component: "HeaderSearch",
      target: "root",
      skin: (a: Record<string, unknown>) => `${a.state}.png`,
    },
  },
};
