import type { Meta, StoryObj } from "@storybook/react-vite";
import * as chrome from "../chrome";

/* Generated by tools/gen-component-stories.mjs from chrome.tsx's own prop types,
   default values and JSDoc. Do not hand-edit: `npm run gen:stories -- --check`
   will fail and the next run will overwrite it. To change the text on the docs
   page, edit the comment above `HeaderSearch` in chrome.tsx. */
const meta = {
  title: "05 Patterns/04 Header search",
  component: chrome.HeaderSearch,
  parameters: {
    layout: "fullscreen",
    docs: {
      description: {
        component:
          "a disclosure that eases open instead of swapping the DOM.",
      },
    },
  },
  argTypes: {
    label: {
      control: "text",
      description: "Accessible name for the field.",
      table: {
        defaultValue: {
          summary: "HEADER_SEARCH_LABEL",
        },
      },
    },
    placeholder: {
      control: "text",
    },
    openLabel: {
      control: "text",
      description: "Name of the submit button while collapsed, and once open.",
    },
    submitLabel: {
      control: "text",
    },
    initialOpen: {
      control: "boolean",
      description: "Whether the field starts expanded.",
    },
  },
  args: {
    label: chrome.HEADER_SEARCH_LABEL,
    placeholder: "Search",
    openLabel: "Open search",
    submitLabel: "Search",
    initialOpen: false,
  },
} satisfies Meta<typeof chrome.HeaderSearch>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  name: "Header search",
};
