import type { Meta, StoryObj } from "@storybook/react-vite";
import * as marketing from "../marketing";

/* Generated by tools/gen-component-stories.mjs from marketing.tsx's own prop types,
   default values and JSDoc. Do not hand-edit: `npm run gen:stories -- --check`
   will fail and the next run will overwrite it. To change the text on the docs
   page, edit the comment above `HeroCarousel` in marketing.tsx. */
const meta = {
  title: "05 Patterns/05 Hero carousel",
  component: marketing.HeroCarousel,
  parameters: {
    layout: "fullscreen",
    docs: {
      description: {
        component:
          "hero slider. Does not auto-advance. 2.2.2 requires a pause control for anything that moves by itself, and a wireframe has nothing to prove by moving. The dots are real buttons with names rather than decorative spans.",
      },
    },
  },
  argTypes: {
    slides: {
      control: "object",
      table: {
        defaultValue: {
          summary: "HERO_SLIDES",
        },
      },
    },
    initialSlide: {
      control: {
        type: "number",
      },
      description: "Which slide is showing on first render. Clamped to the deck.",
    },
    label: {
      control: "text",
      description: "Aria label for the carousel region.",
    },
  },
  args: {
    slides: marketing.HERO_SLIDES,
    initialSlide: 0,
    label: "Featured",
  },
} satisfies Meta<typeof marketing.HeroCarousel>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  name: "Hero carousel",
};

export const OnionSkin: Story = {
  name: "Onion skin (Figma)",
  parameters: {
    docs: { description: { story: "The Figma component laid over this one, first slide, at the 1024px width it was drawn at. The plate is the kit's stock placeholder (the same image is in the design), so what is compared is the scrim, the copy, the CTA and the pager. Switch Onion in the toolbar." } },
    onion: {
      component: "HeroCarousel",
      target: "root",
      skin: () => "default.png",
    },
  },
};
