import type { Meta, StoryObj } from "@storybook/react-vite";
import * as marketing from "../marketing";

/* Generated by tools/gen-component-stories.mjs from marketing.tsx's own prop types,
   default values and JSDoc. Do not hand-edit: `npm run gen:stories -- --check`
   will fail and the next run will overwrite it. To change the text on the docs
   page, edit the comment above `ArrowCta` in marketing.tsx. */
const meta = {
  title: "05 Patterns/06 Arrow CTA",
  component: marketing.ArrowCta,
  parameters: {
    layout: "fullscreen",
    docs: {
      description: {
        component:
          "the repeated conversion pattern. Uppercase label, trailing arrow.",
      },
    },
  },
  argTypes: {
    children: {
      control: false,
      description: "Slot — composed elements, not text.",
      table: {
        defaultValue: {
          summary: "ARROW_CTA_LABEL",
        },
      },
    },
    variant: {
      control: "inline-radio",
      options: ["solid", "outline", "quiet"],
    },
    size: {
      control: "inline-radio",
      options: ["sm", "md", "lg"],
    },
  },
  args: {
    children: marketing.ARROW_CTA_LABEL,
    size: "lg",
  },
} satisfies Meta<typeof marketing.ArrowCta>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  name: "Arrow CTA",
};
