import type { Meta, StoryObj } from "@storybook/react-vite";
import * as ArrowCta from "../ArrowCta";

/* Generated by tools/gen-component-stories.mjs from ArrowCta.tsx's own prop types,
   default values and JSDoc. Do not hand-edit: `npm run gen:stories -- --check`
   will fail and the next run will overwrite it. To change the text on the docs
   page, edit the comment above `ArrowCta` in ArrowCta.tsx. */
const meta = {
  title: "05 Patterns/06 Arrow CTA",
  component: ArrowCta.ArrowCta,
  parameters: {
    layout: "fullscreen",
    docs: {
      description: {
        component:
          "the repeated conversion pattern. Uppercase label, trailing arrow.",
      },
    },
  },
  argTypes: {
    children: {
      control: false,
      description: "Slot — composed elements, not text.",
      table: {
        defaultValue: {
          summary: "ARROW_CTA_LABEL",
        },
      },
    },
    variant: {
      control: "inline-radio",
      options: ["solid", "outline", "quiet"],
    },
    size: {
      control: "inline-radio",
      options: ["sm", "md", "lg"],
    },
  },
  args: {
    children: ArrowCta.ARROW_CTA_LABEL,
    size: "lg",
  },
} satisfies Meta<typeof ArrowCta.ArrowCta>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  name: "Arrow CTA",
};

export const OnionSkin: Story = {
  name: "Onion skin (Figma)",
  parameters: {
    docs: { description: { story: "The Figma component laid over this one. ArrowCta is a Button with an uppercase, tracked, semibold label and a trailing arrow, drawn at lg by default. Switch Onion in the toolbar; variant and size pick the skin." } },
    onion: {
      component: "ArrowCta",
      skin: (a: Record<string, unknown>) => `${a.variant ?? "solid"}-${a.size ?? "lg"}.png`,
    },
  },
};
