import type { Meta, StoryObj } from "@storybook/react-vite";
import * as marketing from "../marketing";

/* Generated by tools/gen-component-stories.mjs from marketing.tsx's own prop types,
   default values and JSDoc. Do not hand-edit: `npm run gen:stories -- --check`
   will fail and the next run will overwrite it. To change the text on the docs
   page, edit the comment above `ProofStrip` in marketing.tsx. */
const meta = {
  title: "05 Patterns/07 Proof strip",
  component: marketing.ProofStrip,
  parameters: {
    layout: "fullscreen",
    docs: {
      description: {
        component:
          "the proof strip. Three claims run together as one pipe-delimited line read as a single run-on sentence to a screen reader. Three labelled figures say the same thing and can be navigated.",
      },
    },
  },
  argTypes: {
    heading: {
      control: "text",
      table: {
        defaultValue: {
          summary: "PROOF_HEADING",
        },
      },
    },
    deck: {
      control: {
        type: "text",
      },
      table: {
        defaultValue: {
          summary: "PROOF_DECK",
        },
      },
    },
    stats: {
      control: "object",
      table: {
        defaultValue: {
          summary: "PROOF_STATS",
        },
      },
    },
    columns: {
      control: "inline-radio",
      options: [1, 2, 3, 4],
    },
  },
  args: {
    heading: marketing.PROOF_HEADING,
    deck: marketing.PROOF_DECK,
    stats: marketing.PROOF_STATS,
    columns: 3,
  },
} satisfies Meta<typeof marketing.ProofStrip>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  name: "Proof strip",
};
