import type { Meta, StoryObj } from "@storybook/react-vite";
import * as marketing from "../marketing";

/* Generated by tools/gen-component-stories.mjs from marketing.tsx's own prop types,
   default values and JSDoc. Do not hand-edit: `npm run gen:stories -- --check`
   will fail and the next run will overwrite it. To change the text on the docs
   page, edit the comment above `SegmentList` in marketing.tsx. */
const meta = {
  title: "05 Patterns/08 Segment list",
  component: marketing.SegmentList,
  parameters: {
    layout: "fullscreen",
    docs: {
      description: {
        component:
          "segment routing, as a real list.",
      },
    },
  },
  argTypes: {
    heading: {
      control: "text",
      table: {
        defaultValue: {
          summary: "SEGMENT_HEADING",
        },
      },
    },
    deck: {
      control: {
        type: "text",
      },
      table: {
        defaultValue: {
          summary: "SEGMENT_DECK",
        },
      },
    },
    audiences: {
      control: "object",
      table: {
        defaultValue: {
          summary: "SEGMENTS",
        },
      },
    },
    reach: {
      control: "object",
      table: {
        defaultValue: {
          summary: "REACH_FACTS",
        },
      },
    },
    reachLabel: {
      control: "text",
      table: {
        defaultValue: {
          summary: "SEGMENT_REACH_LABEL",
        },
      },
    },
    mapLabel: {
      control: "text",
      description: "Aria label for the map region.",
      table: {
        defaultValue: {
          summary: "SEGMENT_MAP_LABEL",
        },
      },
    },
    showMap: {
      control: "boolean",
      description: "false drops the map and gives the copy the full width.",
    },
  },
  args: {
    heading: marketing.SEGMENT_HEADING,
    deck: marketing.SEGMENT_DECK,
    audiences: marketing.SEGMENTS,
    reach: marketing.REACH_FACTS,
    reachLabel: marketing.SEGMENT_REACH_LABEL,
    mapLabel: marketing.SEGMENT_MAP_LABEL,
    showMap: true,
  },
} satisfies Meta<typeof marketing.SegmentList>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  name: "Segment list",
};
