import type { Meta, StoryObj } from "@storybook/react-vite";
import * as marketing from "../marketing";

/* Generated by tools/gen-component-stories.mjs from marketing.tsx's own prop types,
   default values and JSDoc. Do not hand-edit: `npm run gen:stories -- --check`
   will fail and the next run will overwrite it. To change the text on the docs
   page, edit the comment above `SegmentList` in marketing.tsx. */
const meta = {
  title: "05 Patterns/08 Segment list",
  component: marketing.SegmentList,
  parameters: {
    layout: "fullscreen",
    docs: {
      description: {
        component:
          "segment routing, as a real list.",
      },
    },
  },
  argTypes: {
    heading: {
      control: "text",
      table: {
        defaultValue: {
          summary: "SEGMENT_HEADING",
        },
      },
    },
    deck: {
      control: {
        type: "text",
      },
      table: {
        defaultValue: {
          summary: "SEGMENT_DECK",
        },
      },
    },
    audiences: {
      control: "object",
      table: {
        defaultValue: {
          summary: "SEGMENTS",
        },
      },
    },
    reach: {
      control: "object",
      table: {
        defaultValue: {
          summary: "REACH_FACTS",
        },
      },
    },
    reachLabel: {
      control: "text",
      table: {
        defaultValue: {
          summary: "SEGMENT_REACH_LABEL",
        },
      },
    },
    mapLabel: {
      control: "text",
      description: "Aria label for the map region.",
      table: {
        defaultValue: {
          summary: "SEGMENT_MAP_LABEL",
        },
      },
    },
    showMap: {
      control: "boolean",
      description: "false drops the map and gives the copy the full width.",
    },
    mapStyle: {
      control: "text",
      description: "A MapLibre style URL or JSON, passed to the map. Leave it out for the pack's basemap; set it for an offline or house basemap.",
    },
  },
  args: {
    heading: marketing.SEGMENT_HEADING,
    deck: marketing.SEGMENT_DECK,
    audiences: marketing.SEGMENTS,
    reach: marketing.REACH_FACTS,
    reachLabel: marketing.SEGMENT_REACH_LABEL,
    mapLabel: marketing.SEGMENT_MAP_LABEL,
    showMap: true,
  },
} satisfies Meta<typeof marketing.SegmentList>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  name: "Segment list",
};

export const OnionSkin: Story = {
  name: "Onion skin (Figma)",
  args: {"mapStyle":"data:application/json,%7B%22version%22%3A8%2C%22sources%22%3A%7B%22flat%22%3A%7B%22type%22%3A%22raster%22%2C%22tiles%22%3A%5B%22data%3Aimage%2Fpng%3Bbase64%2CiVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAADElEQVR4nGP49esnAAXfAu7EA17oAAAAAElFTkSuQmCC%22%5D%2C%22tileSize%22%3A256%2C%22attribution%22%3A%22%5Cu00a9%20CARTO%2C%20%5Cu00a9%20OpenStreetMap%20contributors%22%7D%7D%2C%22layers%22%3A%5B%7B%22id%22%3A%22ground%22%2C%22type%22%3A%22raster%22%2C%22source%22%3A%22flat%22%7D%5D%7D"},
  parameters: {
    docs: { description: { story: "The Figma SegmentList laid over this one at 1024px: the copy and the audiences list on the left, the map and the reach list on the right. The map is a flat stand-in basemap (no tiles are fetched), so what is compared is the layout and the controls. Switch Onion in the toolbar." } },
    onion: {
      component: "SegmentList",
      target: "root",
      skin: () => "default.png",
    },
  },
};
