import type { Meta, StoryObj } from "@storybook/react-vite";
import * as marketing from "../marketing";

/* Generated by tools/gen-component-stories.mjs from marketing.tsx's own prop types,
   default values and JSDoc. Do not hand-edit: `npm run gen:stories -- --check`
   will fail and the next run will overwrite it. To change the text on the docs
   page, edit the comment above `FeatureGrid` in marketing.tsx. */
const meta = {
  title: "05 Patterns/09 Feature grid",
  component: marketing.FeatureGrid,
  parameters: {
    layout: "fullscreen",
    docs: {
      description: {
        component:
          "the capability grid. A plain list of equal claims, each with a stand-in plate. The column count is a prop rather than a breakpoint: the grid is placed in a container and asked how many it should be, which is a question the page can answer and the viewport cannot.",
      },
    },
  },
  argTypes: {
    categories: {
      control: "object",
      description: "Subject per card, positionally. Short lists cycle, like `kinds` does.",
    },
    heading: {
      control: "text",
      table: {
        defaultValue: {
          summary: "FEATURE_HEADING",
        },
      },
    },
    deck: {
      control: {
        type: "text",
      },
      table: {
        defaultValue: {
          summary: "FEATURE_DECK",
        },
      },
    },
    items: {
      control: "object",
      table: {
        defaultValue: {
          summary: "FEATURES",
        },
      },
    },
    columns: {
      control: "inline-radio",
      options: [1, 2, 3, 4],
    },
    ratio: {
      control: "select",
      options: ["21 / 9", "16 / 9", "16 / 10", "4 / 3", "1 / 1", "3 / 4"],
      description: "Aspect ratio of each card's stand-in photograph.",
    },
  },
  args: {
    heading: marketing.FEATURE_HEADING,
    deck: marketing.FEATURE_DECK,
    items: marketing.FEATURES,
    columns: 3,
    ratio: "4 / 3",
  },
} satisfies Meta<typeof marketing.FeatureGrid>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  name: "Feature grid",
};

export const OnionSkin: Story = {
  name: "Onion skin (Figma)",
  parameters: {
    docs: { description: { story: "The Figma component laid over this one at 1024px: a header and three cards, each a photograph bleeding to the card's edges over a title. Switch Onion in the toolbar." } },
    onion: {
      component: "FeatureGrid",
      target: "root",
      skin: () => "default.png",
    },
  },
};
