import type { Meta, StoryObj } from "@storybook/react-vite";
import * as ArticleFeed from "../ArticleFeed";

/* Generated by tools/gen-component-stories.mjs from ArticleFeed.tsx's own prop types,
   default values and JSDoc. Do not hand-edit: `npm run gen:stories -- --check`
   will fail and the next run will overwrite it. To change the text on the docs
   page, edit the comment above `ArticleFeed` in ArticleFeed.tsx. */
const meta = {
  title: "05 Patterns/10 Article feed",
  component: ArticleFeed.ArticleFeed,
  parameters: {
    layout: "fullscreen",
    docs: {
      description: {
        component:
          "the insights feed. The title sits over the photograph, which is only defensible because the scrim bounds the worst case: text on bare photography cannot be contrast-checked and 1.4.3 still applies to it.",
      },
    },
  },
  argTypes: {
    categories: {
      control: "object",
      description: "Subject per card, positionally. Cycled, like `kinds`.",
    },
    heading: {
      control: "text",
      table: {
        defaultValue: {
          summary: "ARTICLE_FEED_HEADING",
        },
      },
    },
    deck: {
      control: {
        type: "text",
      },
      table: {
        defaultValue: {
          summary: "ARTICLE_FEED_DECK",
        },
      },
    },
    cards: {
      control: "object",
      table: {
        defaultValue: {
          summary: "ARTICLES",
        },
      },
    },
    kinds: {
      control: "object",
      description: "Eyebrow labels, cycled across the cards.",
      table: {
        defaultValue: {
          summary: "ARTICLE_KINDS",
        },
      },
    },
    columns: {
      control: "inline-radio",
      options: [1, 2, 3, 4],
    },
  },
  args: {
    heading: ArticleFeed.ARTICLE_FEED_HEADING,
    deck: ArticleFeed.ARTICLE_FEED_DECK,
    cards: ArticleFeed.ARTICLES,
    kinds: ArticleFeed.ARTICLE_KINDS,
    columns: 4,
  },
} satisfies Meta<typeof ArticleFeed.ArticleFeed>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  name: "Article feed",
};

export const OnionSkin: Story = {
  name: "Onion skin (Figma)",
  parameters: {
    docs: { description: { story: "The Figma component laid over this one at 1024px: a centred header and four portrait cards with their kind and title over a dark scrim. Switch Onion in the toolbar." } },
    onion: {
      component: "ArticleFeed",
      target: "root",
      skin: () => "default.png",
    },
  },
};
