import type { Meta, StoryObj } from "@storybook/react-vite";
import * as marketing from "../marketing";

/* Generated by tools/gen-component-stories.mjs from marketing.tsx's own prop types,
   default values and JSDoc. Do not hand-edit: `npm run gen:stories -- --check`
   will fail and the next run will overwrite it. To change the text on the docs
   page, edit the comment above `EventPromo` in marketing.tsx. */
const meta = {
  title: "05 Patterns/11 Event promo",
  component: marketing.EventPromo,
  parameters: {
    layout: "fullscreen",
    docs: {
      description: {
        component:
          "split media and copy with one action.",
      },
    },
  },
  argTypes: {
    category: {
      control: "text",
      description: "What the photograph is of.",
    },
    eyebrow: {
      control: "text",
      table: {
        defaultValue: {
          summary: "EVENT_EYEBROW",
        },
      },
    },
    heading: {
      control: "text",
      table: {
        defaultValue: {
          summary: "EVENT_HEADING",
        },
      },
    },
    body: {
      control: {
        type: "text",
      },
      table: {
        defaultValue: {
          summary: "EVENT_BODY",
        },
      },
    },
    meta: {
      control: "text",
      table: {
        defaultValue: {
          summary: "EVENT_META",
        },
      },
    },
    ctaLabel: {
      control: "text",
      table: {
        defaultValue: {
          summary: "EVENT_CTA_LABEL",
        },
      },
    },
    seed: {
      control: {
        type: "range",
        min: 1,
        max: 6,
        step: 1,
      },
      description: "1-6. Picks the stand-in photograph.",
    },
    ratio: {
      control: "select",
      options: ["21 / 9", "16 / 9", "16 / 10", "4 / 3", "1 / 1", "3 / 4"],
    },
  },
  args: {
    eyebrow: marketing.EVENT_EYEBROW,
    heading: marketing.EVENT_HEADING,
    body: marketing.EVENT_BODY,
    meta: marketing.EVENT_META,
    ctaLabel: marketing.EVENT_CTA_LABEL,
    seed: 5,
    ratio: "16 / 10",
  },
} satisfies Meta<typeof marketing.EventPromo>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  name: "Event promo",
};
