import type { Meta, StoryObj } from "@storybook/react-vite";
import * as templates from "../templates";

/* Generated by tools/gen-component-stories.mjs from templates.tsx's own prop types,
   default values and JSDoc. Do not hand-edit: `npm run gen:stories -- --check`
   will fail and the next run will overwrite it. To change the text on the docs
   page, edit the comment above `LeadForm` in templates.tsx. */
const meta = {
  title: "05 Patterns/12 Lead form",
  component: templates.LeadForm,
  parameters: {
    layout: "fullscreen",
    docs: {
      description: {
        component:
          "the lead capture form.",
      },
    },
  },
  argTypes: {
    heading: {
      control: "text",
      table: {
        defaultValue: {
          summary: "LEAD_HEADING",
        },
      },
    },
    deck: {
      control: {
        type: "text",
      },
    },
    fields: {
      control: "object",
      table: {
        defaultValue: {
          summary: "LEAD_FIELDS",
        },
      },
    },
    columns: {
      control: "inline-radio",
      options: [1, 2, 3, 4],
    },
    industryLabel: {
      control: "text",
    },
    industryPlaceholder: {
      control: "text",
      description: "The disabled first option, which is what makes the select required-able.",
    },
    industries: {
      control: "object",
      table: {
        defaultValue: {
          summary: "LEAD_CATEGORIES",
        },
      },
    },
    detailLabel: {
      control: "text",
    },
    detailRows: {
      control: {
        type: "number",
      },
      description: "Visible rows on the detail textarea.",
    },
    showVerification: {
      control: "boolean",
      description: "false drops the verification note.",
    },
    verificationTitle: {
      control: "text",
    },
    verificationBody: {
      control: {
        type: "text",
      },
    },
    submitLabel: {
      control: "text",
    },
  },
  args: {
    heading: templates.LEAD_HEADING,
    deck: "Fields marked required must be completed before the form can be sent.",
    fields: templates.LEAD_FIELDS,
    columns: 2,
    industryLabel: "Category",
    industryPlaceholder: "Choose a category",
    industries: templates.LEAD_CATEGORIES,
    detailLabel: "What are you working on",
    detailRows: 5,
    showVerification: true,
    verificationTitle: "Verification",
    verificationBody: "A challenge sits here in production. Any challenge used must offer a non-cognitive alternative — 3.3.8 does not accept a puzzle as the only route through.",
    submitLabel: "Send",
  },
} satisfies Meta<typeof templates.LeadForm>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  name: "Lead form",
};
