import type { Meta, StoryObj } from "@storybook/react-vite";
import * as SiteFooter from "../SiteFooter";

/* Generated by tools/gen-component-stories.mjs from SiteFooter.tsx's own prop types,
   default values and JSDoc. Do not hand-edit: `npm run gen:stories -- --check`
   will fail and the next run will overwrite it. To change the text on the docs
   page, edit the comment above `SiteFooter` in SiteFooter.tsx. */
const meta = {
  title: "05 Patterns/13 Site footer",
  component: SiteFooter.SiteFooter,
  parameters: {
    layout: "fullscreen",
    docs: {
      description: {
        component:
          "the inverted closing band.",
      },
    },
  },
  argTypes: {
    legalLinks: {
      control: "object",
      table: {
        defaultValue: {
          summary: "FOOTER_LEGAL_LINKS",
        },
      },
    },
    navLinks: {
      control: "object",
      table: {
        defaultValue: {
          summary: "FOOTER_NAV_LINKS",
        },
      },
    },
    socialLinks: {
      control: "object",
      table: {
        defaultValue: {
          summary: "FOOTER_SOCIAL_LINKS",
        },
      },
    },
    socialLabel: {
      control: "text",
      description: "Aria label for the social list.",
    },
    subscribeLabel: {
      control: "text",
      table: {
        defaultValue: {
          summary: "FOOTER_SUBSCRIBE_LABEL",
        },
      },
    },
    subscribeCta: {
      control: "text",
    },
    copyright: {
      control: "text",
      table: {
        defaultValue: {
          summary: "FOOTER_COPYRIGHT",
        },
      },
    },
    seed: {
      control: {
        type: "range",
        min: 1,
        max: 6,
        step: 1,
      },
      description: "1-6. Picks the stand-in mark.",
    },
  },
  args: {
    legalLinks: SiteFooter.FOOTER_LEGAL_LINKS,
    navLinks: SiteFooter.FOOTER_NAV_LINKS,
    socialLinks: SiteFooter.FOOTER_SOCIAL_LINKS,
    socialLabel: "Social",
    subscribeLabel: SiteFooter.FOOTER_SUBSCRIBE_LABEL,
    subscribeCta: "Sign up now",
    copyright: SiteFooter.FOOTER_COPYRIGHT,
    seed: 4,
  },
} satisfies Meta<typeof SiteFooter.SiteFooter>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  name: "Site footer",
};

export const OnionSkin: Story = {
  name: "Onion skin (Figma)",
  parameters: {
    docs: { description: { story: "The Figma component laid over this one, at the 1024px section width it was drawn at. Switch Onion in the toolbar. There is one skin." } },
    onion: {
      component: "SiteFooter",
      target: "root",
      skin: () => "default.png",
    },
  },
};
