import type { Meta, StoryObj } from "@storybook/react-vite";
import * as chrome from "../chrome";

/* Generated by tools/gen-component-stories.mjs from chrome.tsx's own prop types,
   default values and JSDoc. Do not hand-edit: `npm run gen:stories -- --check`
   will fail and the next run will overwrite it. To change the text on the docs
   page, edit the comment above `PageHero` in chrome.tsx. */
const meta = {
  title: "05 Patterns/14 Page hero",
  component: chrome.PageHero,
  parameters: {
    layout: "fullscreen",
    docs: {
      description: {
        component:
          "breadcrumb over a tinted title band.",
      },
    },
  },
  argTypes: {
    title: {
      control: "text",
      table: {
        defaultValue: {
          summary: "PAGE_HERO_TITLE",
        },
      },
    },
    crumbs: {
      control: "object",
      description: "Ancestors only. The current page is appended from `title`.",
      table: {
        defaultValue: {
          summary: "PAGE_CRUMBS",
        },
      },
    },
    deck: {
      control: {
        type: "text",
      },
      table: {
        defaultValue: {
          summary: "PAGE_HERO_DECK",
        },
      },
    },
    breadcrumbLabel: {
      control: "text",
      description: "Aria label for the breadcrumb nav.",
    },
  },
  args: {
    title: chrome.PAGE_HERO_TITLE,
    crumbs: chrome.PAGE_CRUMBS,
    deck: chrome.PAGE_HERO_DECK,
    breadcrumbLabel: "Breadcrumb",
  },
} satisfies Meta<typeof chrome.PageHero>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  name: "Page hero",
};
