import type { Meta, StoryObj } from "@storybook/react-vite";
import * as catalog from "../catalog";

/* Generated by tools/gen-component-stories.mjs from catalog.tsx's own prop types,
   default values and JSDoc. Do not hand-edit: `npm run gen:stories -- --check`
   will fail and the next run will overwrite it. To change the text on the docs
   page, edit the comment above `TileGrid` in catalog.tsx. */
const meta = {
  title: "05 Patterns/15 Tile grid",
  component: catalog.TileGrid,
  parameters: {
    layout: "fullscreen",
    docs: {
      description: {
        component:
          "dense catalogue grid, a short label over a plate.",
      },
    },
  },
  argTypes: {
    heading: {
      control: "object",
      description: "false drops the heading, for a page that already names the section.",
      table: {
        defaultValue: {
          summary: "TILE_GRID_HEADING",
        },
      },
    },
    compact: {
      control: "boolean",
      description: "Tighter padding when nested in a sample page that already has a hero.",
    },
    tiles: {
      control: "object",
      table: {
        defaultValue: {
          summary: "TILES",
        },
      },
    },
    columns: {
      control: "inline-radio",
      options: [1, 2, 3, 4],
    },
    ratio: {
      control: "select",
      options: ["21 / 9", "16 / 9", "16 / 10", "4 / 3", "1 / 1", "3 / 4"],
      description: "Aspect ratio of each tile's stand-in photograph.",
    },
  },
  args: {
    heading: catalog.TILE_GRID_HEADING,
    compact: false,
    tiles: catalog.TILES,
    columns: 3,
    ratio: "16 / 9",
  },
} satisfies Meta<typeof catalog.TileGrid>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  name: "Tile grid",
};

export const OnionSkin: Story = {
  name: "Onion skin (Figma)",
  parameters: {
    docs: { description: { story: "The Figma component laid over this one at 1024px, nine tiles as the grid lays them out (four to a row: columns is a minimum tile width). The stock plates are the same images in the design, so what is compared is the card, its radii, the type and the grid. Switch Onion in the toolbar." } },
    onion: {
      component: "TileGrid",
      skin: () => "default.png",
    },
  },
};
