import type { Meta, StoryObj } from "@storybook/react-vite";
import * as catalog from "../catalog";

/* Generated by tools/gen-component-stories.mjs from catalog.tsx's own prop types,
   default values and JSDoc. Do not hand-edit: `npm run gen:stories -- --check`
   will fail and the next run will overwrite it. To change the text on the docs
   page, edit the comment above `HubCards` in catalog.tsx. */
const meta = {
  title: "05 Patterns/16 Hub cards",
  component: catalog.HubCards,
  parameters: {
    layout: "fullscreen",
    docs: {
      description: {
        component:
          "the alternate taxonomy: title, summary, read-more.",
      },
    },
  },
  argTypes: {
    heading: {
      control: "text",
      table: {
        defaultValue: {
          summary: "HUB_CARDS_HEADING",
        },
      },
    },
    items: {
      control: "object",
      table: {
        defaultValue: {
          summary: "HUB_CARDS",
        },
      },
    },
    columns: {
      control: "inline-radio",
      options: [1, 2, 3, 4],
    },
    readMoreLabel: {
      control: "text",
      description: "Link text on each card. The card title follows it, visually hidden.",
    },
  },
  args: {
    heading: catalog.HUB_CARDS_HEADING,
    items: catalog.HUB_CARDS,
    columns: 2,
    readMoreLabel: "Read more",
  },
} satisfies Meta<typeof catalog.HubCards>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  name: "Hub cards",
};
