import type { Meta, StoryObj } from "@storybook/react-vite";
import * as catalog from "../catalog";

/* Generated by tools/gen-component-stories.mjs from catalog.tsx's own prop types,
   default values and JSDoc. Do not hand-edit: `npm run gen:stories -- --check`
   will fail and the next run will overwrite it. To change the text on the docs
   page, edit the comment above `CtaBlocks` in catalog.tsx. */
const meta = {
  title: "05 Patterns/17 CTA blocks",
  component: catalog.CtaBlocks,
  parameters: {
    layout: "fullscreen",
    docs: {
      description: {
        component:
          "paired mid-funnel banners.",
      },
    },
  },
  argTypes: {
    blocks: {
      control: "object",
      table: {
        defaultValue: {
          summary: "CTA_BLOCKS",
        },
      },
    },
    columns: {
      control: "inline-radio",
      options: [1, 2, 3, 4],
    },
  },
  args: {
    blocks: catalog.CTA_BLOCKS,
    columns: 2,
  },
} satisfies Meta<typeof catalog.CtaBlocks>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  name: "CTA blocks",
};

export const OnionSkin: Story = {
  name: "Onion skin (Figma)",
  parameters: {
    docs: { description: { story: "The Figma component laid over this one at 1024px: an inverse block with an outline ArrowCta and a sunken block with a solid one, the button radius the concentric remainder of the block's. Switch Onion in the toolbar." } },
    onion: {
      component: "CtaBlocks",
      target: "root",
      skin: () => "default.png",
    },
  },
};
