import type { Meta, StoryObj } from "@storybook/react-vite";
import * as catalog from "../catalog";

/* Generated by tools/gen-component-stories.mjs from catalog.tsx's own prop types,
   default values and JSDoc. Do not hand-edit: `npm run gen:stories -- --check`
   will fail and the next run will overwrite it. To change the text on the docs
   page, edit the comment above `FilterBar` in catalog.tsx. */
const meta = {
  title: "05 Patterns/18 Filter bar",
  component: catalog.FilterBar,
  parameters: {
    layout: "fullscreen",
    docs: {
      description: {
        component:
          "content-type filters. A toggle-button group rather than styled links, so the active state is programmatic (aria-pressed) instead of a colour a screen reader cannot see.",
      },
    },
  },
  argTypes: {
    types: {
      control: "object",
      table: {
        defaultValue: {
          summary: "FILTER_TYPES",
        },
      },
    },
    icons: {
      control: "object",
      description: "Leading icon per type. A type with no entry gets the tag icon.",
      table: {
        defaultValue: {
          summary: "FILTER_ICONS",
        },
      },
    },
    initialType: {
      control: "text",
      description: "Which chip is pressed on first render. Falls back to the first type.",
    },
    label: {
      control: "text",
      description: "Aria label for the filter group.",
    },
  },
  args: {
    types: catalog.FILTER_TYPES,
    icons: catalog.FILTER_ICONS,
    initialType: "All",
    label: "Filter by type",
  },
} satisfies Meta<typeof catalog.FilterBar>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  name: "Filter bar",
};
