import type { Meta, StoryObj } from "@storybook/react-vite";
import * as catalog from "../catalog";

/* Generated by tools/gen-component-stories.mjs from catalog.tsx's own prop types,
   default values and JSDoc. Do not hand-edit: `npm run gen:stories -- --check`
   will fail and the next run will overwrite it. To change the text on the docs
   page, edit the comment above `MediaCards` in catalog.tsx. */
const meta = {
  title: "05 Patterns/19 Media cards",
  component: catalog.MediaCards,
  parameters: {
    layout: "fullscreen",
    docs: {
      description: {
        component:
          "media promos with a type badge and a duration.",
      },
    },
  },
  argTypes: {
    heading: {
      control: "text",
      table: {
        defaultValue: {
          summary: "MEDIA_CARDS_HEADING",
        },
      },
    },
    items: {
      control: "object",
      table: {
        defaultValue: {
          summary: "MEDIA_ITEMS",
        },
      },
    },
    icons: {
      control: "object",
      table: {
        defaultValue: {
          summary: "MEDIA_ICONS",
        },
      },
    },
    columns: {
      control: "inline-radio",
      options: [1, 2, 3, 4],
    },
    ratio: {
      control: "select",
      options: ["21 / 9", "16 / 9", "16 / 10", "4 / 3", "1 / 1", "3 / 4"],
      description: "Aspect ratio of each card's stand-in photograph.",
    },
  },
  args: {
    heading: catalog.MEDIA_CARDS_HEADING,
    items: catalog.MEDIA_ITEMS,
    icons: catalog.MEDIA_ICONS,
    columns: 3,
    ratio: "16 / 9",
  },
} satisfies Meta<typeof catalog.MediaCards>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  name: "Media cards",
};
