import type { Meta, StoryObj } from "@storybook/react-vite";
import * as catalog from "../catalog";

/* Generated by tools/gen-component-stories.mjs from catalog.tsx's own prop types,
   default values and JSDoc. Do not hand-edit: `npm run gen:stories -- --check`
   will fail and the next run will overwrite it. To change the text on the docs
   page, edit the comment above `PeopleDirectory` in catalog.tsx. */
const meta = {
  title: "05 Patterns/20 People directory",
  component: catalog.PeopleDirectory,
  parameters: {
    layout: "fullscreen",
    docs: {
      description: {
        component:
          "filter bar over a four-up person grid.",
      },
    },
  },
  argTypes: {
    heading: {
      control: "text",
      table: {
        defaultValue: {
          summary: "PEOPLE_DIRECTORY_HEADING",
        },
      },
    },
    people: {
      control: "object",
      table: {
        defaultValue: {
          summary: "STAFF",
        },
      },
    },
    columns: {
      control: "inline-radio",
      options: [1, 2, 3, 4],
    },
    locations: {
      control: "object",
      table: {
        defaultValue: {
          summary: "PEOPLE_PLACES",
        },
      },
    },
    companies: {
      control: "object",
      table: {
        defaultValue: {
          summary: "PEOPLE_TEAMS",
        },
      },
    },
    initialLocation: {
      control: "text",
      description: "Selected on first render; \"\" leaves the any-value option showing.",
    },
    initialCompany: {
      control: "text",
    },
    ctaLabel: {
      control: "text",
    },
    filterLabel: {
      control: "text",
      description: "Aria label for the filter form.",
    },
  },
  args: {
    heading: catalog.PEOPLE_DIRECTORY_HEADING,
    people: catalog.STAFF,
    columns: 4,
    locations: catalog.PEOPLE_PLACES,
    companies: catalog.PEOPLE_TEAMS,
    initialLocation: "",
    initialCompany: "",
    ctaLabel: "View all people",
    filterLabel: "Filter the directory",
  },
} satisfies Meta<typeof catalog.PeopleDirectory>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  name: "People directory",
};
