import type { Meta, StoryObj } from "@storybook/react-vite";
import * as templates from "../templates";

/* Generated by tools/gen-component-stories.mjs from templates.tsx's own prop types,
   default values and JSDoc. Do not hand-edit: `npm run gen:stories -- --check`
   will fail and the next run will overwrite it. To change the text on the docs
   page, edit the comment above `SegmentPage` in templates.tsx. */
const meta = {
  title: "05 Patterns/21 Segment page",
  component: templates.SegmentPage,
  parameters: {
    layout: "fullscreen",
    docs: {
      description: {
        component:
          "the audience landing pattern.",
      },
    },
  },
  argTypes: {
    title: {
      control: "text",
      table: {
        defaultValue: {
          summary: "SEGMENT_TITLE",
        },
      },
    },
    crumbs: {
      control: "object",
      table: {
        defaultValue: {
          summary: "SEGMENT_CRUMBS",
        },
      },
    },
    deck: {
      control: {
        type: "text",
      },
      table: {
        defaultValue: {
          summary: "SEGMENT_DECK",
        },
      },
    },
    intro: {
      control: {
        type: "text",
      },
      table: {
        defaultValue: {
          summary: "SEGMENT_INTRO",
        },
      },
    },
    capabilitiesHeading: {
      control: "text",
    },
    capabilities: {
      control: "object",
      table: {
        defaultValue: {
          summary: "SEGMENT_FEATURES",
        },
      },
    },
    ctaHeading: {
      control: "text",
      table: {
        defaultValue: {
          summary: "SEGMENT_CTA_HEADING",
        },
      },
    },
    ctaLabel: {
      control: "text",
    },
    seed: {
      control: {
        type: "range",
        min: 1,
        max: 6,
        step: 1,
      },
      description: "1-6. Picks the stand-in photograph.",
    },
    ratio: {
      control: "select",
      options: ["21 / 9", "16 / 9", "16 / 10", "4 / 3", "1 / 1", "3 / 4"],
    },
  },
  args: {
    title: templates.SEGMENT_TITLE,
    crumbs: templates.SEGMENT_CRUMBS,
    deck: templates.SEGMENT_DECK,
    intro: templates.SEGMENT_INTRO,
    capabilitiesHeading: "Capabilities",
    capabilities: templates.SEGMENT_FEATURES,
    ctaHeading: templates.SEGMENT_CTA_HEADING,
    ctaLabel: "Contact us",
    seed: 2,
    ratio: "4 / 3",
  },
} satisfies Meta<typeof templates.SegmentPage>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  name: "Segment page",
};
