import type { Meta, StoryObj } from "@storybook/react-vite";
import * as templates from "../templates";

/* Generated by tools/gen-component-stories.mjs from templates.tsx's own prop types,
   default values and JSDoc. Do not hand-edit: `npm run gen:stories -- --check`
   will fail and the next run will overwrite it. To change the text on the docs
   page, edit the comment above `SubBrandPage` in templates.tsx. */
const meta = {
  title: "05 Patterns/22 Sub-brand page",
  component: templates.SubBrandPage,
  parameters: {
    layout: "fullscreen",
    docs: {
      description: {
        component:
          "portfolio and acquisition brand page.",
      },
    },
  },
  argTypes: {
    title: {
      control: "text",
      table: {
        defaultValue: {
          summary: "SUBBRAND_TITLE",
        },
      },
    },
    crumbs: {
      control: "object",
      table: {
        defaultValue: {
          summary: "SUBBRAND_CRUMBS",
        },
      },
    },
    body: {
      control: {
        type: "text",
      },
      table: {
        defaultValue: {
          summary: "SUBBRAND_BODY",
        },
      },
    },
    facts: {
      control: "object",
      table: {
        defaultValue: {
          summary: "SUBBRAND_FACTS",
        },
      },
    },
    ctaLabel: {
      control: "text",
    },
    seed: {
      control: {
        type: "range",
        min: 1,
        max: 6,
        step: 1,
      },
      description: "1-6. Picks the stand-in photograph.",
    },
    ratio: {
      control: "select",
      options: ["21 / 9", "16 / 9", "16 / 10", "4 / 3", "1 / 1", "3 / 4"],
    },
  },
  args: {
    title: templates.SUBBRAND_TITLE,
    crumbs: templates.SUBBRAND_CRUMBS,
    body: templates.SUBBRAND_BODY,
    facts: templates.SUBBRAND_FACTS,
    ctaLabel: "Visit the site",
    seed: 6,
    ratio: "3 / 2",
  },
} satisfies Meta<typeof templates.SubBrandPage>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  name: "Sub-brand page",
};

export const OnionSkin: Story = {
  name: "Onion skin (Figma)",
  parameters: {
    docs: { description: { story: "The Figma component laid over this one at 1024px: a PageHero, a narrow column of photograph and button beside an intro and a list of facts. Switch Onion in the toolbar." } },
    onion: {
      component: "SubBrandPage",
      target: "root",
      skin: () => "default.png",
    },
  },
};
