import type { Meta, StoryObj } from "@storybook/react-vite";
import * as templates from "../templates";

/* Generated by tools/gen-component-stories.mjs from templates.tsx's own prop types,
   default values and JSDoc. Do not hand-edit: `npm run gen:stories -- --check`
   will fail and the next run will overwrite it. To change the text on the docs
   page, edit the comment above `ArticlePage` in templates.tsx. */
const meta = {
  title: "05 Patterns/23 Article page",
  component: templates.ArticlePage,
  parameters: {
    layout: "fullscreen",
    docs: {
      description: {
        component:
          "the long-form content template.",
      },
    },
  },
  argTypes: {
    title: {
      control: "text",
      table: {
        defaultValue: {
          summary: "ARTICLE_TITLE",
        },
      },
    },
    crumbs: {
      control: "object",
      table: {
        defaultValue: {
          summary: "ARTICLE_CRUMBS",
        },
      },
    },
    kind: {
      control: "text",
      table: {
        defaultValue: {
          summary: "ARTICLE_KIND",
        },
      },
    },
    meta: {
      control: "text",
    },
    lede: {
      control: {
        type: "text",
      },
      table: {
        defaultValue: {
          summary: "ARTICLE_LEDE",
        },
      },
    },
    body: {
      control: {
        type: "text",
      },
      description: "One paragraph per entry, above the section heading.",
      table: {
        defaultValue: {
          summary: "ARTICLE_BODY",
        },
      },
    },
    sectionHeading: {
      control: "text",
      table: {
        defaultValue: {
          summary: "ARTICLE_SECTION_HEADING",
        },
      },
    },
    sectionBody: {
      control: {
        type: "text",
      },
      table: {
        defaultValue: {
          summary: "ARTICLE_SECTION_BODY",
        },
      },
    },
    showAuthor: {
      control: "boolean",
      description: "false drops the byline card off the foot of the article.",
    },
    authorName: {
      control: "text",
      table: {
        defaultValue: {
          summary: "ARTICLE_AUTHOR_NAME",
        },
      },
    },
    authorRole: {
      control: "text",
      table: {
        defaultValue: {
          summary: "ARTICLE_AUTHOR_ROLE",
        },
      },
    },
    seed: {
      control: {
        type: "range",
        min: 1,
        max: 6,
        step: 1,
      },
      description: "1-6. Picks the stand-in portrait.",
    },
  },
  args: {
    title: templates.ARTICLE_TITLE,
    crumbs: templates.ARTICLE_CRUMBS,
    kind: templates.ARTICLE_KIND,
    meta: "12 March 2026 · 8 min read",
    lede: templates.ARTICLE_LEDE,
    body: templates.ARTICLE_BODY,
    sectionHeading: templates.ARTICLE_SECTION_HEADING,
    sectionBody: templates.ARTICLE_SECTION_BODY,
    showAuthor: true,
    authorName: templates.ARTICLE_AUTHOR_NAME,
    authorRole: templates.ARTICLE_AUTHOR_ROLE,
    seed: 1,
  },
} satisfies Meta<typeof templates.ArticlePage>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  name: "Article page",
};

export const OnionSkin: Story = {
  name: "Onion skin (Figma)",
  parameters: {
    docs: { description: { story: "The Figma component laid over this one at 1024px: a PageHero, then a 485px reading column (kind chip and date, lede, paragraphs, a section, a flat byline card). The skin is the hero and the column exported separately and placed, because Figma caps an export at 1024px. Switch Onion in the toolbar." } },
    onion: {
      component: "ArticlePage",
      target: "root",
      skin: () => "default.png",
    },
  },
};
