import type { Meta, StoryObj } from "@storybook/react-vite";
import * as EventList from "../EventList";

/* Generated by tools/gen-component-stories.mjs from EventList.tsx's own prop types,
   default values and JSDoc. Do not hand-edit: `npm run gen:stories -- --check`
   will fail and the next run will overwrite it. To change the text on the docs
   page, edit the comment above `EventList` in EventList.tsx. */
const meta = {
  title: "05 Patterns/24 Event list",
  component: EventList.EventList,
  parameters: {
    layout: "fullscreen",
    docs: {
      description: {
        component:
          "event rows: date, title, location, action.",
      },
    },
  },
  argTypes: {
    heading: {
      control: "text",
      table: {
        defaultValue: {
          summary: "EVENT_LIST_HEADING",
        },
      },
    },
    events: {
      control: "object",
      table: {
        defaultValue: {
          summary: "EVENT_ROWS",
        },
      },
    },
    ctaLabel: {
      control: "text",
    },
  },
  args: {
    heading: EventList.EVENT_LIST_HEADING,
    events: EventList.EVENT_ROWS,
    ctaLabel: "Register",
  },
} satisfies Meta<typeof EventList.EventList>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  name: "Event list",
};

export const OnionSkin: Story = {
  name: "Onion skin (Figma)",
  parameters: {
    docs: { description: { story: "The Figma component laid over this one at 1024px: a heading and three rows, each with the date and place in mono above the title, an outline button at the right and a hairline under it. Switch Onion in the toolbar." } },
    onion: {
      component: "EventList",
      target: "root",
      skin: () => "default.png",
    },
  },
};
