import type { Meta, StoryObj } from "@storybook/react-vite";
import * as templates from "../templates";

/* Generated by tools/gen-component-stories.mjs from templates.tsx's own prop types,
   default values and JSDoc. Do not hand-edit: `npm run gen:stories -- --check`
   will fail and the next run will overwrite it. To change the text on the docs
   page, edit the comment above `ApplyForm` in templates.tsx. */
const meta = {
  title: "05 Patterns/25 Apply form",
  component: templates.ApplyForm,
  parameters: {
    layout: "fullscreen",
    docs: {
      description: {
        component:
          "single-column form with a file input and a consent checkbox.",
      },
    },
  },
  argTypes: {
    heading: {
      control: "text",
      table: {
        defaultValue: {
          summary: "APPLY_HEADING",
        },
      },
    },
    fields: {
      control: "object",
      table: {
        defaultValue: {
          summary: "APPLY_FIELDS",
        },
      },
    },
    roleLabel: {
      control: "text",
    },
    rolePlaceholder: {
      control: "text",
    },
    roles: {
      control: "object",
      table: {
        defaultValue: {
          summary: "APPLY_ROLES",
        },
      },
    },
    resumeLabel: {
      control: "text",
    },
    resumeHint: {
      control: "text",
    },
    resumeAccept: {
      control: "text",
      description: "Value of the file input's accept attribute.",
    },
    consentLabel: {
      control: "text",
    },
    submitLabel: {
      control: "text",
    },
  },
  args: {
    heading: templates.APPLY_HEADING,
    fields: templates.APPLY_FIELDS,
    roleLabel: "Role of interest",
    rolePlaceholder: "Choose a role",
    roles: templates.APPLY_ROLES,
    resumeLabel: "Résumé",
    resumeHint: "PDF or Word, up to 5 MB.",
    resumeAccept: ".pdf,.doc,.docx",
    consentLabel: "I agree to this application being stored for recruitment purposes",
    submitLabel: "Submit application",
  },
} satisfies Meta<typeof templates.ApplyForm>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  name: "Apply form",
};

export const OnionSkin: Story = {
  name: "Onion skin (Figma)",
  parameters: {
    docs: { description: { story: "The Figma component laid over this one at its own width (the form's measure, 517px): a heading over one column of fields, a file Field, a consent checkbox and a solid button. The file input and checkbox are the browser's own controls; the design draws stand-ins. Switch Onion in the toolbar." } },
    onion: {
      component: "ApplyForm",
      target: "root",
      skin: () => "default.png",
    },
  },
};
