import type { Meta, StoryObj } from "@storybook/react-vite";
import * as marketing from "../marketing";

/* Generated by tools/gen-component-stories.mjs from marketing.tsx's own prop types,
   default values and JSDoc. Do not hand-edit: `npm run gen:stories -- --check`
   will fail and the next run will overwrite it. To change the text on the docs
   page, edit the comment above `Hero` in marketing.tsx. */
const meta = {
  title: "05 Patterns/26 Hero",
  component: marketing.Hero,
  parameters: {
    layout: "fullscreen",
    docs: {
      description: {
        component:
          "the static hero: the top of a page that is not a carousel. Eyebrow, title, lede, actions and a visual, every one optional but the title, so the minimal hero is this component with less in it. `layout` is the one coordinate: stacked puts the visual under the copy, split puts it beside. The copy comes first in the DOM either way, so reading order is title, lede, actions, visual on both sides of the wrap. The visual is the page's largest paint, so the plate loads eagerly at high priority and holds its ratio so nothing shifts. Nothing animates in.",
      },
    },
  },
  argTypes: {
    eyebrow: {
      control: "text",
      description: "A short line above the title. Leave empty for none.",
      table: {
        defaultValue: {
          summary: "HERO_EYEBROW",
        },
      },
    },
    title: {
      control: "text",
      table: {
        defaultValue: {
          summary: "HERO_TITLE",
        },
      },
    },
    lede: {
      control: {
        type: "text",
      },
      description: "One or two sentences under the title. Leave empty for none.",
      table: {
        defaultValue: {
          summary: "HERO_LEDE",
        },
      },
    },
    cta: {
      control: "text",
      description: "The primary action's label. Leave empty for no primary action.",
      table: {
        defaultValue: {
          summary: "HERO_CTA",
        },
      },
    },
    secondary: {
      control: "text",
      description: "A second, quieter action beside the first. Leave empty for none.",
      table: {
        defaultValue: {
          summary: "HERO_SECONDARY",
        },
      },
    },
    actions: {
      control: "inline-radio",
      options: ["buttons", "capture"],
      description: "buttons: the CTA and the secondary. capture: an inline form (one field, `cta` as its submit) in their place.",
    },
    captureLabel: {
      control: "text",
      description: "The capture field's label (capture only).",
      table: {
        defaultValue: {
          summary: "HERO_CAPTURE_LABEL",
        },
      },
    },
    captureHint: {
      control: "text",
      description: "A line under the capture field: what they are signing up for, how often (capture only).",
      table: {
        defaultValue: {
          summary: "HERO_CAPTURE_HINT",
        },
      },
    },
    layout: {
      control: "inline-radio",
      options: ["stacked", "split"],
      description: "stacked: the visual under the copy. split: copy and visual side by side, stacking when the box cannot hold two.",
    },
    media: {
      control: "inline-radio",
      options: ["plate", "none"],
      description: "plate draws the stand-in photograph; none leaves the hero as copy only.",
    },
    ratio: {
      control: "select",
      options: ["21 / 9", "16 / 9", "16 / 10", "4 / 3", "1 / 1", "3 / 4"],
      description: "Aspect ratio of the visual.",
    },
    seed: {
      control: {
        type: "range",
        min: 1,
        max: 6,
        step: 1,
      },
      description: "1-6. Picks the stand-in photograph; deterministic so screenshots match.",
    },
    category: {
      control: "text",
      description: "What the photograph is of, named on the plate while no stock is registered.",
    },
  },
  args: {
    eyebrow: marketing.HERO_EYEBROW,
    title: marketing.HERO_TITLE,
    lede: marketing.HERO_LEDE,
    cta: marketing.HERO_CTA,
    secondary: marketing.HERO_SECONDARY,
    actions: "buttons",
    captureLabel: marketing.HERO_CAPTURE_LABEL,
    captureHint: marketing.HERO_CAPTURE_HINT,
    layout: "stacked",
    media: "plate",
    ratio: "16 / 9",
    seed: 2,
  },
} satisfies Meta<typeof marketing.Hero>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  name: "Hero",
};

export const OnionSkin: Story = {
  name: "Onion skin (Figma)",
  parameters: {
    docs: { description: { story: "The Figma Hero laid over this one at 1024px: stacked and split, with buttons or with the capture form. The plate is a captured stand-in with its corner drawn in Figma. Switch Onion in the toolbar; layout and actions in Controls pick the skin." } },
    onion: {
      component: "Hero",
      target: "root",
      skin: (a: Record<string, unknown>) => `${a.layout}-${a.actions ?? "buttons"}.png`,
    },
  },
};
