/* GENERATED by tools/gen-scene-vocabulary.mjs from src/scene/kinds.mjs and the
   components' own prop types. Do not edit: change the component or kinds.mjs
   and run the generator; `--check` fails when this file has drifted.

   A kind's props: an array is its allowed values; "text", "flag", "integer",
   "list" and "icon" are kinds of value. */

export const PACKS = {
  "bathing-bagels": "Bathing Bagels",
  "door-shop": "Door Shop",
  "mohave": "Mohave",
  "muncheese": "Muncheese",
  "tk": "TK",
  "wandas": "Wanda’s",
  "wireframe-dark": "Wireframe dark",
  "wireframe": "Wireframe"
};

export const KINDS = {
  "stack": {
    "name": "Stack",
    "about": "children in a column",
    "children": true,
    "props": {
      "gap": [
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9
      ],
      "align": [
        "start",
        "center",
        "end",
        "stretch"
      ],
      "justify": [
        "start",
        "center",
        "end",
        "between"
      ]
    }
  },
  "row": {
    "name": "Row",
    "about": "children in one line, no wrapping",
    "children": true,
    "props": {
      "gap": [
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9
      ],
      "align": [
        "start",
        "center",
        "end",
        "stretch"
      ],
      "justify": [
        "start",
        "center",
        "end",
        "between"
      ]
    }
  },
  "inline": {
    "name": "Inline",
    "about": "children in a line that wraps: a set of tags",
    "children": true,
    "props": {
      "gap": [
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9
      ],
      "align": [
        "start",
        "center",
        "end",
        "stretch"
      ],
      "justify": [
        "start",
        "center",
        "end",
        "between"
      ]
    }
  },
  "grid": {
    "name": "Grid",
    "about": "children in up to cols columns that fold on a narrow width; ratio makes two unequal columns",
    "children": true,
    "props": {
      "gap": [
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9
      ],
      "cols": [
        1,
        2,
        3,
        4
      ],
      "fixed": "flag",
      "ratio": [
        "2:1",
        "1:2",
        "3:1",
        "1:3"
      ],
      "align": [
        "start",
        "center",
        "end",
        "stretch"
      ],
      "justify": [
        "start",
        "center",
        "end",
        "between"
      ]
    }
  },
  "split": {
    "name": "Split",
    "about": "two equal halves",
    "children": true,
    "props": {
      "gap": [
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9
      ],
      "align": [
        "start",
        "center",
        "end",
        "stretch"
      ],
      "justify": [
        "start",
        "center",
        "end",
        "between"
      ]
    }
  },
  "sidebar": {
    "name": "Sidebar",
    "about": "a narrow first child beside a wide second; side end puts the narrow one last",
    "children": true,
    "props": {
      "gap": [
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9
      ],
      "side": [
        "start",
        "end"
      ],
      "align": [
        "start",
        "center",
        "end",
        "stretch"
      ],
      "justify": [
        "start",
        "center",
        "end",
        "between"
      ]
    }
  },
  "center": {
    "name": "Center",
    "about": "a centred measure",
    "children": true,
    "props": {
      "gap": [
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9
      ],
      "width": [
        "narrow",
        "default",
        "wide"
      ],
      "align": [
        "start",
        "center",
        "end",
        "stretch"
      ],
      "justify": [
        "start",
        "center",
        "end",
        "between"
      ]
    }
  },
  "card": {
    "name": "Card",
    "about": "a surface; holds a card-header or card-title, card-body, card-footer and any other parts",
    "children": true,
    "props": {
      "variant": [
        "default",
        "flat",
        "bare"
      ]
    }
  },
  "card-header": {
    "name": "Card header",
    "about": "the top of a card: an eyebrow above its card-title and a subtitle under it",
    "children": [
      "card-title"
    ],
    "within": [
      "card"
    ],
    "props": {
      "eyebrow": "text",
      "subtitle": "text"
    }
  },
  "card-title": {
    "name": "Card title",
    "about": "a card's heading",
    "text": "children"
  },
  "card-body": {
    "name": "Card body",
    "about": "a card's paragraph",
    "text": "children"
  },
  "card-footer": {
    "name": "Card footer",
    "about": "the foot of a card, usually its buttons",
    "children": true
  },
  "heading": {
    "name": "Heading",
    "about": "a heading outside a card; level is its place in the outline, look how it appears when that differs",
    "text": "children",
    "props": {
      "level": [
        1,
        2,
        3,
        4,
        5,
        6
      ],
      "look": [
        "title",
        "eyebrow",
        "body",
        "caption",
        "small",
        "display",
        "heading-l",
        "heading-m",
        "heading-s",
        "heading-xs",
        "lead",
        "metric"
      ]
    }
  },
  "text": {
    "name": "Text",
    "about": "a paragraph; look sets a text style (lead, small, caption, metric…)",
    "text": "children",
    "props": {
      "look": [
        "title",
        "eyebrow",
        "body",
        "caption",
        "small",
        "display",
        "heading-l",
        "heading-m",
        "heading-s",
        "heading-xs",
        "lead",
        "metric"
      ]
    }
  },
  "eyebrow": {
    "name": "Eyebrow",
    "about": "a small uppercase label above a heading",
    "text": "children",
    "props": {
      "emphasis": [
        "quiet"
      ]
    }
  },
  "media": {
    "name": "Media",
    "about": "where a picture goes, drawn in the pack; label says what it stands in for",
    "props": {
      "ratio": [
        "16 / 9",
        "4 / 3",
        "1 / 1",
        "3 / 4",
        "21 / 9"
      ],
      "label": "text",
      "texture": [
        "hatch",
        "dots",
        "rule",
        "grid",
        "noise",
        "weave",
        "chevron",
        "grain",
        "paper",
        "stone",
        "mist",
        "grit",
        "halftone",
        "brand",
        "signature",
        "none"
      ]
    }
  },
  "divider": {
    "name": "Divider",
    "about": "a rule between sections"
  },
  "icon": {
    "name": "Icon",
    "about": "an icon on its own; give it a label only when it is the only thing saying what it means",
    "props": {
      "icon": "icon",
      "size": [
        "sm",
        "md",
        "lg"
      ],
      "label": "text"
    }
  },
  "button": {
    "name": "Button",
    "about": "a button; tone danger for destructive actions; with an icon and no text it is icon-only",
    "text": "children",
    "props": {
      "variant": [
        "quiet",
        "solid",
        "outline"
      ],
      "tone": [
        "neutral",
        "danger"
      ],
      "size": [
        "sm",
        "md",
        "lg"
      ],
      "pressed": "flag",
      "full": "flag",
      "busy": "flag",
      "icon": "icon",
      "iconPosition": [
        "leading",
        "trailing"
      ]
    }
  },
  "button-group": {
    "name": "Button group",
    "about": "two or three related buttons in a row (the rest behind More); its text is the group's accessible name",
    "text": "label",
    "children": [
      "button"
    ],
    "props": {
      "align": [
        "start",
        "end"
      ],
      "max": [
        2,
        3
      ],
      "equal": "flag",
      "size": [
        "sm",
        "md",
        "lg"
      ],
      "moreLabel": "text"
    }
  },
  "chip": {
    "name": "Chip",
    "about": "a small label: a tag, a status; interactive and pressed make it a filter",
    "text": "children",
    "props": {
      "emphasis": [
        "default",
        "strong",
        "quiet"
      ],
      "interactive": "flag",
      "pressed": "flag",
      "icon": "icon"
    }
  },
  "field": {
    "name": "Field",
    "about": "a labelled input, textarea or select; chars sizes it to the answer; options are a select's choices",
    "props": {
      "label": "text",
      "hint": "text",
      "error": "text",
      "required": "flag",
      "optional": "flag",
      "control": [
        "input",
        "select",
        "textarea"
      ],
      "chars": [
        2,
        3,
        4,
        5,
        10,
        20,
        30
      ],
      "prefix": "text",
      "suffix": "text",
      "maxChars": "integer",
      "options": "list",
      "type": [
        "text",
        "email",
        "password",
        "number",
        "search",
        "tel",
        "url",
        "date"
      ],
      "readOnly": "flag"
    }
  },
  "alert": {
    "name": "Alert",
    "about": "a message with a status",
    "text": "children",
    "props": {
      "status": [
        "info",
        "success",
        "warning",
        "danger"
      ],
      "title": "text"
    }
  },
  "choice-group": {
    "name": "Choice group",
    "about": "a question answered by choice cards; its text is the question",
    "text": "legend",
    "children": [
      "choice"
    ],
    "props": {
      "hideLegend": "flag",
      "type": [
        "radio",
        "checkbox"
      ],
      "required": "flag",
      "columns": [
        1,
        2,
        3,
        4
      ],
      "hint": "text"
    }
  },
  "choice": {
    "name": "Choice",
    "about": "one choice card: its text is the option's name; description and meta (a price, Recommended) are optional",
    "text": "title",
    "within": [
      "choice-group"
    ],
    "props": {
      "description": "text",
      "meta": "text",
      "disabled": "flag"
    }
  }
};
