#!/usr/bin/env node
/**
 * Token export — the contract, resolved, as JSON.
 *
 * Not a copy of the CSS source. This loads the kit in a real browser, mounts
 * one element per context, and reads getComputedStyle for every contract slot,
 * so what comes out is what the cascade actually produced: pack references
 * followed to their literal, calc() evaluated, density applied, the inverse
 * context resolved separately. A token file generated by parsing CSS text
 * would report `var(--wf-300)`; this reports `rgb(208, 208, 208)`.
 *
 * That difference is the point. The JSON is what a brand hands to a native
 * team, a Figma sync, or an email template — none of which can resolve a CSS
 * custom property — and it has to be the same values the site ships.
 *
 *   npm run tokens                    -> dist/tokens/<pack>.json + index.json
 *   npm run tokens -- --pack wireframe
 *   npm run tokens -- --stdout
 *
 * Shape: grouped by family, each leaf { $value, $type, source }, plus a flat
 * `resolved` map for anything that just wants name -> value. Contexts that
 * remap slots (inverse, each density) appear as their own blocks so a consumer
 * can see that --tk-text-primary has more than one answer.
 */

import { chromium } from "playwright";
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { resolve, dirname } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");

const argv = process.argv.slice(2);
const toStdout = argv.includes("--stdout");
const packIdx = argv.indexOf("--pack");
const onlyPack = packIdx > -1 ? argv[packIdx + 1] : null;

/* The contract is whatever 02-property.css registers plus the motion slots,
   which have no @property syntax to be registered under. One source of truth:
   if a slot is not declared there, it is not contract. */
const propertySrc = await readFile(resolve(ROOT, "src/css/02-property.css"), "utf8");
const registered = [...propertySrc.matchAll(/@property\s+(--tk-[\w-]+)/g)].map((m) => m[1]);
const scaleSrc = await readFile(resolve(ROOT, "src/css/03-scale.css"), "utf8");
const motion = [...scaleSrc.matchAll(/(--tk-motion-[\w-]+)\s*:/g)].map((m) => m[1]);
/* The raw curves and durations too. They are not registered — @property has no
   syntax for a transition shorthand or a cubic-bezier — but a consumer outside
   CSS needs the curve itself, not only the slots that pair it with a duration.
   Kept identical to src/tokens/slots.ts so the CLI export and Tokens/Export
   describe the same contract. */
const timing = [...scaleSrc.matchAll(/(--tk-(?:duration|ease)-[\w-]+)\s*:/g)].map((m) => m[1]);
/* Slots the components read that are declared in a pack or in the scale but
   not registered with @property: status colours, quiet-action fills, shadows,
   the type scale. They are just as much contract — Alert, Guidance and Field
   read status-*, Button's outline and quiet variants read action-quiet-*, and
   no component can be drawn without sizes and weights — and a token file that
   left them out sent a Figma sync back to the CSS for values the export
   claimed to have. */
const packSrc = (
  await Promise.all(["wireframe", "wireframe-dark"].map((p) => readFile(resolve(ROOT, `src/css/packs/${p}.css`), "utf8")))
).join(String.fromCharCode(10));
const declared = [
  ...packSrc.matchAll(/(--tk-(?:status|action-quiet|shadow|font)-[\w-]+)\s*:/g),
  ...scaleSrc.matchAll(/(--tk-(?:size|weight|leading|tracking|font)-[\w-]+)\s*:/g),
].map((m) => m[1]);
const SLOTS = [...new Set([...registered, ...motion, ...timing, ...declared])].sort();

/* The six specimen brands are packs like any other, so a Figma sync can carry
   them: every brand a client could arrive as is one more mode. */
const PACKS = ["wireframe", "wireframe-dark", "tk", "door-shop", "mohave", "bathing-bagels", "wandas", "muncheese"].filter((p) => !onlyPack || p === onlyPack);
const DENSITIES = ["default", "compact", "comfortable"];

const typeOf = (name, value) => {
  if (/^(rgb|rgba|#|color\()/.test(value)) return "color";
  if (/^--tk-(space|radius|size|measure|plate|search|target|focus)/.test(name)) return "dimension";
  if (/^--tk-(duration)/.test(name)) return "duration";
  if (/^--tk-(ease)/.test(name)) return "cubicBezier";
  if (/^--tk-motion/.test(name)) return "transition";
  if (/^--tk-(weight)/.test(name)) return "fontWeight";
  if (/^--tk-(status|action-quiet)/.test(name) && !/^(rgb|#|color\()/.test(value)) return "color";
  if (/^--tk-font/.test(name)) return "fontFamily";
  if (/^--tk-(leading|tracking|density|scrim)/.test(name)) return "number";
  if (/^--tk-shadow/.test(name)) return "shadow";
  return "other";
};

const family = (name) => {
  const rest = name.replace("--tk-", "");
  const head = rest.split("-")[0];
  return { group: head, leaf: rest.slice(head.length + 1) || head };
};

/* Written to disk and navigated to, rather than handed to setContent: a page
   created from setContent has an about:blank origin and cannot load a file://
   stylesheet, so every computed value comes back empty. The probe lives beside
   the CSS so the @import chain resolves relatively. */
const probePath = resolve(ROOT, "dist/.token-probe.html");
await mkdir(dirname(probePath), { recursive: true });
await writeFile(
  probePath,
  `<!doctype html><meta charset="utf-8">
<link rel="stylesheet" href="../src/css/index.css">
<link rel="stylesheet" href="../src/css/specimens.css">
<body><div id="probe"></div></body>`,
);

const browser = await chromium.launch(
  process.env.TOKENKIT_CHROMIUM ? { executablePath: process.env.TOKENKIT_CHROMIUM } : {},
);
const page = await browser.newPage();
await page.goto(pathToFileURL(probePath).href, { waitUntil: "networkidle" });

const out = {};
for (const pack of PACKS) {
  const contexts = {};

  for (const density of DENSITIES) {
    for (const on of ["default", "inverse"]) {
      const values = await page.evaluate(
        ({ pack, density, on, slots }) => {
          const probe = document.getElementById("probe");
          probe.innerHTML = "";
          const host = document.createElement("div");
          host.setAttribute("data-brand", pack);
          if (density !== "default") host.setAttribute("data-density", density);
          const inner = document.createElement("div");
          if (on === "inverse") inner.setAttribute("data-on", "inverse");
          host.appendChild(inner);
          probe.appendChild(host);

          const cs = getComputedStyle(inner);

          /* A registered <length> whose value came through an unregistered
             intermediate still reports as `calc(1.5rem * 1)`. That is the
             computed value of the custom property, and it is not what anyone
             asking for a token file wants — a native team cannot evaluate a
             calc. So anything dimensional is pushed through a real property
             and read back, which is the only way to get the used value.
             Colours and transitions are already literal and are left alone. */
          const ruler = document.createElement("div");
          ruler.style.position = "absolute";
          ruler.style.visibility = "hidden";
          inner.appendChild(ruler);

          const render = (slot, raw) => {
            if (/^--tk-tracking-/.test(slot)) return raw; // em is the token; px at some font size is not
            if (!/calc\(|[\d.]+(rem|em|ch|ex|vw|vh|%)/.test(raw)) return raw;
            if (/^(rgb|#|color\()/.test(raw)) return raw;
            ruler.style.width = "";
            ruler.style.width = `var(${slot})`;
            const w = getComputedStyle(ruler).width;
            return /^[\d.]+px$/.test(w) ? w : raw;
          };

          const o = {};
          for (const s of slots) {
            const v = cs.getPropertyValue(s).trim();
            if (v) o[s] = render(s, v);
          }
          ruler.remove();
          return o;
        },
        { pack, density, on, slots: SLOTS },
      );

      const key = on === "inverse" ? `${density}/inverse` : density;
      const grouped = {};
      for (const [name, value] of Object.entries(values)) {
        const { group, leaf } = family(name);
        grouped[group] ??= {};
        grouped[group][leaf] = {
          $value: value,
          $type: typeOf(name, value),
          source: name,
        };
      }
      contexts[key] = { tokens: grouped, resolved: values };
    }
  }

  out[pack] = {
    $description: `tokenkit contract resolved under the "${pack}" pack. Generated by tools/tokens-export.mjs from computed styles — every value is what the browser produced, not what the source said.`,
    generated: new Date().toISOString(),
    slotCount: SLOTS.length,
    contexts,
  };
}

await browser.close();

if (toStdout) {
  console.log(JSON.stringify(out, null, 2));
  process.exit(0);
}

const dir = resolve(ROOT, "dist/tokens");
await mkdir(dir, { recursive: true });
for (const [pack, data] of Object.entries(out)) {
  await writeFile(resolve(dir, `${pack}.json`), JSON.stringify(data, null, 2) + "\n");
}
await writeFile(
  resolve(dir, "index.json"),
  JSON.stringify(
    {
      $description: "Every pack, every context, resolved.",
      packs: Object.keys(out),
      slotCount: SLOTS.length,
      contexts: Object.keys(out[PACKS[0]].contexts),
    },
    null,
    2,
  ) + "\n",
);

console.log(`\ntokenkit token export — ${SLOTS.length} contract slots`);
for (const [pack, data] of Object.entries(out)) {
  console.log(`  dist/tokens/${pack}.json — ${Object.keys(data.contexts).length} contexts`);
}
console.log();
